---
title:  'Notas sobre Verificação de Identidade Digital'
author:
- 'Ermogenes Palacio'
- 'Eduardo Amaro Bueno'
affiliation: 'Prodam/SP'
keywords: ['identidade digital', 'governo']
abstract: |
  Notas sobre o processo de verificação de identidade digital, com foco na prestação de serviços públicos por entidades governamentais.
date: 'Março de 2022'
language: pt-BR
...