name: Creta PDF from README

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  convert: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0

    - name: Build
      uses: baileyjm02/markdown-to-pdf@v1
      with:
        input_dir: ./
        output_dir: ./
        images_dir: ./img
        image_import: ./img
        build_html: false

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        retention-days: 90
      
    - name: Commit PDF
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Gera PDF atualizado
