name: Create PDF from README

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build
      uses: docker://pandoc/latex
      with:
        args: >-  # allows you to break string into multiple lines
          --standalone
          --from=markdown
          --to=pdf
          --output=./Notas-identidade-digital.pdf
          --number-sections
          --table-of-contents
          --pdf-engine-opt=--no-toc-relocation
          --shift-heading-level-by=-1
          -V papersize=a4
          -V links-as-notes=true
          ./README.md
    - name: Commit PDF
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Gera PDF atualizado
