name: Create PDF from README

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  convert: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0

    - name: Build
      uses: lothindir/pandoc-markdown-action@v0.1
      with:
        markdown: "README.md"
        pdf: "Notas-identidade-digital"
    
    - name: Build
      uses: docker://pandoc/core:2.9
      with:
        args: >-  # allows you to break string into multiple lines
          --standalone
          --output=Notas-identidade-digital.pdf
          README.md
      
    - name: Commit PDF
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Gera PDF atualizado
