name: Creta PDF from README

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  convert_md: 
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 1

    - name: Create PDF
      uses: scottypate/md-to-pdf@v0.1.1
      env: {
        PDF_DIR: './'
      }

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        retention-days: 90
      
    - name: Commit PDF
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Gera PDF atualizado
